# Generated by Django 3.2.8 on 2021-11-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=1, upload_to='marketplace'),
            preserve_default=False,
        ),
    ]
